#!/bin/sh
# shellcheck disable=SC2015,SC2086
has() {
  case "$(command -v $1 2>/dev/null)" in
    alias*|"") return 1
  esac
}
deps() {
  deps="curl" # Make sure deps can be found
  for i in $deps; do
    has $i || {
      echo "$i IS MISSING!"; exit 1
    }
  done
# Check for ssl
  IFS=': '; curl -V | while read -r fe ex; do 
    [ "$fe" = "Protocols" ] && {(
      for i in $ex; do
        [ "$i" = "https" ] && { return 0; }
      done
      return 1;
    ) && { return 0; } || { echo "SSL MISSING..."; exit 1; };}
  done
}
deps && echo "VALID"
